### ISSUE TITLE
Groove Editor doesn't work with JGraph 5.6 

### ISSUE THREAD

**Issue by rensink** [nl-utwente-groove/code#16]
Exception in thread "main" java.lang.NoSuchMethodError:
org.jgraph.graph.GraphLayoutCache.addObserver\(Ljava/util/Observer;\)V

Reported by: *anonymous

**Comment by rensink** [comment]
Logged In: YES 
user\_id=1124041

We will upgrade to later jgraph versions eventually.
Unfortunately our experience is that this involves a
non-negligable amount of work. Please indicate the urgency
of your request.

Original comment by: rensink

**Comment by rensink** [comment]
- **status**: pending-remind --> closed-remind

Original comment by: sf-robot

**Comment by rensink** [comment]
Logged In: YES 
user\_id=1312539

This Tracker item was closed automatically by the system. It was
previously set to a Pending status, and the original submitter
did not respond within 14 days \(the time period specified by
the administrator of this Tracker\).

Original comment by: sf-robot
